// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4HWSzn83Y2uRBCAg_br7pPKIqY1FQD8',
    appId: '1:597059876557:web:8e33092b21c3a182b05b84',
    messagingSenderId: '597059876557',
    projectId: 'yap-app-e3d9c',
    authDomain: 'yap-app-e3d9c.firebaseapp.com',
    storageBucket: 'yap-app-e3d9c.appspot.com',
    measurementId: 'G-3QG61ZNFH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiYoCtcXWK2fKehfgklXzEAAE-a8S6y8',
    appId: '1:597059876557:android:359957c9c1717691b05b84',
    messagingSenderId: '597059876557',
    projectId: 'yap-app-e3d9c',
    storageBucket: 'yap-app-e3d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArEI1UHEVcQP64lG2ETztITQx5A7Q0YZI',
    appId: '1:597059876557:ios:316d39d69d171bd4b05b84',
    messagingSenderId: '597059876557',
    projectId: 'yap-app-e3d9c',
    storageBucket: 'yap-app-e3d9c.appspot.com',
    iosBundleId: 'com.example.yap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArEI1UHEVcQP64lG2ETztITQx5A7Q0YZI',
    appId: '1:597059876557:ios:316d39d69d171bd4b05b84',
    messagingSenderId: '597059876557',
    projectId: 'yap-app-e3d9c',
    storageBucket: 'yap-app-e3d9c.appspot.com',
    iosBundleId: 'com.example.yap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4HWSzn83Y2uRBCAg_br7pPKIqY1FQD8',
    appId: '1:597059876557:web:b7516100c1aefdf4b05b84',
    messagingSenderId: '597059876557',
    projectId: 'yap-app-e3d9c',
    authDomain: 'yap-app-e3d9c.firebaseapp.com',
    storageBucket: 'yap-app-e3d9c.appspot.com',
    measurementId: 'G-LV903MFSME',
  );
}
